# Generated by Django 3.0.3 on 2020-02-26 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App17', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_pic',
            new_name='profile_pic',
        ),
    ]
